resolver: haskell-gi-339-walkaround-snapshot.yaml

packages:
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- examples

extra-deps: []

nix:
  packages: [pkgconfig, gnome3.gobjectIntrospection, gnome3.gtk]
